services:
  web:
    build: .
    command: gunicorn my_project.wsgi:application --bind 0.0.0.0:1274
    ports:
      - "1274:1274"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
